Update install

diff --git a/install b/install
--- a/install
+++ b/install
@@ -79,4 +79,6 @@ echo
     elif [[ $lightdm = "n" ]]; then
     echo "$(tput setaf 1)						Enjoy void linux$(tput sgr 0)"
     else
+    echo "Invalid option."
+    exit 1  
 fi
