Update install

diff --git a/install b/install
--- a/install
+++ b/install
@@ -24,6 +24,9 @@ echo
             modprobe kvm-amd
 
             elif [[ $pass = "n" ]]; then
+            else
+            echo "Invalid option. EXITING!"
+            exit 1        
         fi
     elif [[ $video = "a" ]]; then
         sudo xbps-install -Sy $(cat INSTALL/3_ati)
